name: "pa11y"
on:
  issue_comment:
    types: [created, edited]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:

  check_comment:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.trim_comment.outputs.should_run }}
      should_run_sitemap: ${{ steps.trim_comment.outputs.should_run_sitemap }}
    steps:
      - name: Trim comment
        id: trim_comment
        run: |
          COMMENT=$(echo "${{ github.event.comment.body }}" | xargs)
          if [ "$COMMENT" == "/run-pa11y-action" ]; then
            echo "::set-output name=should_run::true"
          else
            echo "::set-output name=should_run::false"
          fi

          if [ "$COMMENT" == "/run-pa11y-action-sitemap" ]; then
            echo "::set-output name=should_run_sitemap::true"
          else
            echo "::set-output name=should_run_sitemap::false"
          fi
          
  pa11y-ci:
    needs: check_comment
    if: (github.event_name == 'issue_comment' && github.event.issue.pull_request) && (needs.check_comment.outputs.should_run == 'true' || needs.check_comment.outputs.should_run_sitemap == 'true')
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR that audit has begun
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Pa11y Audit has begun, please wait for the pending results...'
            })  
            
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0 

      - name: Install specific dependencies
        run: |
          yarn add pa11y-ci pa11y-ci-reporter-html xml2js

      - name: Setup Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Get Chrome path
        run: echo "CHROME_PATH=$(which google-chrome-stable)" >> $GITHUB_ENV 

      - name: Update pa11y config with Chrome path
        run: >
          jq '.defaults.chromeLaunchConfig.executablePath = env.CHROME_PATH'
          .pa11yci.json > .pa11yci.tmp.json && mv .pa11yci.tmp.json
          .pa11yci.json

      - name: Update pa11y config JSON
        if: needs.check_comment.outputs.should_run == 'true'
        run: node ./.github/workflows/scripts/extract-urls.js
        env:
          SITEMAP_URL: https://www.8451.com/sitemap-0.xml
        
      - name: Run pa11y-ci
        continue-on-error: true
        if: needs.check_comment.outputs.should_run == 'true'
        run: |
          sudo yarn run pa11y-ci
    
      - name: Run pa11y-ci on sitemap
        if: needs.check_comment.outputs.should_run_sitemap == 'true'
        run: |
          sudo yarn run pa11y-ci --sitemap https://www.8451.com/sitemap-0.xml
    

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: pa11y-ci-report
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Provide Deploy Link
        uses: actions/github-script@v6
        with:
          script: |
            OUTPUT_URL="https://CFsylvester.github.io/pa11y/pa11y-ci-report/"
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Deployed Pa11y Audit Results: ${OUTPUT_URL}`
            })  
